version: "2.3"

services:
  oauth_task:
    container_name: oauth_task
    build:
      context: .
      dockerfile: Dockerfile
    command: gomon
    restart: always
    environment:
      - JWT_SECRET=oauth
      - DEFAULT_USER=arthamanudeep@gmail.com
      - USER_DB_HOST=oauth_mongodb
      - USER_DB_NAME=user
      - USER_DB_USERNAME=guest
      - USER_DB_PASSWORD=guest
      - GOOGLE_REDIRECT_URL=http://localhost:3000/callback
      - GOOGLE_CLIENT_ID={client_id}
      - GOOGLE_CLIENT_SECRET={client_secret}
    volumes:
      - .:/go/src/oauth/
    ports:
      - "3000:3000"
networks:
  default:
    external:
      name: oauth
